language: objective-c
cache:
  bundler: true
  directories:
  - node_modules
  - build/cache
env:
  global:
  - secure: cmK7r29eJ3JLWw6hwWmdkFASX40ciedftmamXzoOEtZMvEeAvdnjIIgcYQ/NO0+51WMlnnrEekB7h7khKvxgfCQ3S8H9Zi3vTNSKXONPcrNbLfze7FjY63yy5VsHK+PmD6Fmnj3Pl1HpQpzDaRWPrGq/uM2UYiDTpMw3K+OGPTI=
  - secure: aEroqDGI9P3ZxnsH7bLYoM1v8BWk4DyzqlO3yznSxiHbLnj2eHq8ehmjk2LaeuzsWTfxYXUfeg5WnxWP9OC3n+Yfsv7jUlhOwH2YbNssoe6dhYw3/8BPd8Iu4qUJB8rmRYx4h7PUViSO7zUe56sRdjoyZ28mm60j/BKKctdHB3M=
before_script:
- brew update
- brew upgrade xctool || true
- brew install curl
- npm install
script: cd $TRAVIS_BUILD_DIR && .build/build
before_deploy:
- mkdir -p dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- mkdir -p dpl_s3/latest
- cp build/**/*.zip dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- cp build/darwin-x64/Gateblu.dmg dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- cp -rfp dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}/* dpl_s3/latest
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: M0aUEjuuihPDcxZ9lyCo3HqGvOPmiDRnnq4UIwXrC9xTukBS2dfyDKC1sCcn1ijeGtwuw3HUGAVR/hglO13RCdKxTO1xnr4+iljxVOiVH0J3o8tqk3Is7TovmD7P8GpcI2KCgmMDf2ngq9jQWvs4tB6QGil0VcMvwe/6nTeQeMQ=
  bucket: gateblu
  upload-dir: gateblu-ui
  region: us-west-2
  skip_cleanup: true
  local-dir: dpl_s3
  on:
    tags: true
    all_branches: true
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: sqrt@octoblu.com
  api_key:
    secure: "JgeXPAYKIqEduKlCPqkMnYQSr1cmpFw678lRW6JE3u77bTYEG1T3a+qZhyb/Y53FZ9qJiQ48JiH9t1AkPCC/0WCh7Yy2t51k1qqdvSVbXnWAcVFBbBjH0B19+sPP6rgLj4TvqdHISeVLVyY3vEzQLXdW0vZHWyCm1aRfgJuAFBg="
  on:
    tags: true
    all_branches: true

