language: objective-c
cache:
  bundler: true
  directories:
  - node_modules
  - build/cache
  - /Library/Caches/Homebrew
  - /opt/homebrew-cask/Caskroom/
env:
  global:
  - secure: cmK7r29eJ3JLWw6hwWmdkFASX40ciedftmamXzoOEtZMvEeAvdnjIIgcYQ/NO0+51WMlnnrEekB7h7khKvxgfCQ3S8H9Zi3vTNSKXONPcrNbLfze7FjY63yy5VsHK+PmD6Fmnj3Pl1HpQpzDaRWPrGq/uM2UYiDTpMw3K+OGPTI=
  - secure: aEroqDGI9P3ZxnsH7bLYoM1v8BWk4DyzqlO3yznSxiHbLnj2eHq8ehmjk2LaeuzsWTfxYXUfeg5WnxWP9OC3n+Yfsv7jUlhOwH2YbNssoe6dhYw3/8BPd8Iu4qUJB8rmRYx4h7PUViSO7zUe56sRdjoyZ28mm60j/BKKctdHB3M=
before_install:
- npm install npm -g
before_script:
- brew update
- brew upgrade xctool || true
- brew install Caskroom/cask/xquartz
- brew install wine
- brew install curl
- npm install
script: cd $TRAVIS_BUILD_DIR && .build/build
before_deploy:
- mkdir -p dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- mkdir -p dpl_s3/latest
- cp build/**/*.zip dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- cp build/darwin-x64/Gateblu.dmg dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
- cp -rfp dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}/* dpl_s3/latest
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key:
    secure: A7BIpbw8inwuqTqyD+aVW9T/2uyQjjpdRhNhv0WBsL1jxJWSMwuwV1PaBka7SgrBvXRRvHjY626js0cIZYWpdz4+RwV8w1a9q9nXbmxtH3LSvIgLIfs4hrFrQvZvgZvFb0iZQnr6LNG1chuMJHyNOqwfqoEmynWZDDsN0wVxj4Q=
  bucket: gateblu
  upload-dir: gateblu-ui
  region: us-west-2
  skip_cleanup: true
  local-dir: dpl_s3
  on:
    tags: true
    all_branches: master
- provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: "ewo2E6Ugivr1xw7VbahYZPE3m4gZeidr89jxvCjhTjHKpVI6W9vX1li5Zz/SPnXTsWhT0CG4mw4m1BLmsVj35hiao59AAPSBlczpz9RuAp0wHSmlpMbpgGSBDZxvYUNX3FIhp4qcLyCI29Vtcjj6vEQQ9ZVSTG1L8CoqmbE9bWk="
  on:
    tags: true
    all_branches: master
