#!/bin/bash
mkdir -p dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
mkdir -p dpl_s3/latest
cp build/**/*.zip dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
cp build/darwin-x64/Gateblu.dmg dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}
cp -rfp dpl_s3/${TRAVIS_TAG:-$TRAVIS_COMMIT}/* dpl_s3/latest
