#!/bin/bash
if [ "$KEY_PASSWORD" == "" ]; then
  echo "KEY_PASSWORD is blank"
  exit 1
fi
.build/build
mkdir -p build
mkdir -p dpl_s3/commit
mkdir -p dpl_s3/latest
cp build/**/*.zip dpl_s3/commit
cp build/darwin-x64/Gateblu.dmg dpl_s3/commit
cp -rfp dpl_s3/commit/* dpl_s3/latest
