#!/bin/sh
echo "Exciting Electrons..."

PLATFORMS="darwin-x64 linux-x64 linux-ia32 win32-ia32 win32-x64"
START_DIR=`pwd`
SCRIPT_DIR=$START_DIR/.build
BUILD_DIR=$START_DIR/build
ELECTRON_VERSION=0.33.2
ulimit -n 8192
APP_DIR=$BUILD_DIR/app
APP_ARCHIVE=$BUILD_DIR/app.asar
CACHE_DIR=$BUILD_DIR/cache

rm -rf $APP_DIR
mkdir -p $BUILD_DIR $CACHE_DIR/electron

echo "Installing node_modules..."
npm install --silent
node_modules/.bin/gulp

echo "Copying app..."
cp -rfp app $BUILD_DIR

echo "Installing app node_modules..."
cd $APP_DIR
npm install --production --silent

APP_VERSION=`cat $START_DIR/package.json | grep 'version' | awk '{print $2}' | tr -d '"' | tr -d ','`

$START_DIR/node_modules/.bin/asar pack $APP_DIR $APP_ARCHIVE

for ELECTRON_PLATFORM in $PLATFORMS; do
  cd $CACHE_DIR/electron

  echo "Building ($ELECTRON_PLATFORM)..."

  JUST_ELECTRON_PLATFORM=`echo $ELECTRON_PLATFORM | sed "s/-x64//" | sed "s/-ia32//"`
  JUST_ELECTRON_ARCH=`echo $ELECTRON_PLATFORM | sed "s/darwin-//" | sed "s/linux-//" | sed "s/win32-//"`

  PLATFORM_BUILD_DIR=$BUILD_DIR/$ELECTRON_PLATFORM
  PLATFORM_SCRIPT_DIR=$SCRIPT_DIR/$ELECTRON_PLATFORM
  platform_build_script=$PLATFORM_SCRIPT_DIR/build
  sudo rm -rf $PLATFORM_BUILD_DIR
  mkdir -p $PLATFORM_BUILD_DIR
  cd $PLATFORM_BUILD_DIR

  $START_DIR/node_modules/.bin/electron-packager $START_DIR/app Gateblu \
      --platform=$JUST_ELECTRON_PLATFORM \
      --arch=$JUST_ELECTRON_ARCH \
      --version=$ELECTRON_VERSION \
      --icon=$START_DIR/assets/icon.ico \
      --out=$CACHE_DIR \
      --cache=$CACHE_DIR/electron \
      --overwrite \
      --asar=$APP_ARCHIVE \
      --version-string.CompanyName=Octoblu \
      --version-string.ProductName=Gateblu \
      --version-string.ProductVersion=$APP_VERSION

  echo "Copying Gateblu app..."

  cp -rfp $CACHE_DIR/Gateblu-$ELECTRON_PLATFORM/Gateblu* $PLATFORM_BUILD_DIR

  if [ ! -f $platform_build_script ]; then
    echo "Could not find $platform_build_script"
    exit 1
  fi

  export ELECTRON_PLATFORM SCRIPT_DIR PLATFORM_BUILD_DIR KEY_PASSWORD BUILD_DIR APP_DIR PLATFORM_SCRIPT_DIR APP_ARCHIVE

  echo "Running platform script..."
  $platform_build_script

  if [ $! ]; then
    echo "$platform_build_script Failed!"
    exit 1
  fi
done

cd $START_DIR
