#!/bin/sh
echo "** Exciting Electrons..."

if [ -z "$PLATFORMS" ]; then
  PLATFORMS="darwin-x64 linux-x64 linux-ia32 win32-ia32 win32-x64"
fi
START_DIR=`pwd`
SCRIPT_DIR=$START_DIR/.build
BUILD_DIR=$START_DIR/build
ASSETS_DIR=$START_DIR/assets
ELECTRON_VERSION=0.33.3
ulimit -n 8192
APP_DIR=$BUILD_DIR/app
APP_ARCHIVE=$BUILD_DIR/app.asar
CACHE_DIR=$BUILD_DIR/cache

# Initial Sudo so I don't forget
sudo touch $CACHE_DIR/.touchme

rm -rf $APP_DIR
mkdir -p $BUILD_DIR $CACHE_DIR/electron

echo "** Installing node_modules..."
npm install --silent
node_modules/.bin/gulp

echo "** Copying app..."
cp -rfp app $BUILD_DIR

echo "** Installing app node_modules..."
cd $APP_DIR
npm install --production --silent

APP_VERSION=`cat $START_DIR/package.json | grep 'version' | awk '{print $2}' | tr -d '"' | tr -d ','`

$START_DIR/node_modules/.bin/asar pack $APP_DIR $APP_ARCHIVE

for ELECTRON_PLATFORM in $PLATFORMS; do
  cd $CACHE_DIR/electron

  echo "** Building [$ELECTRON_PLATFORM]..."

  PLATFORM_BUILD_DIR=$BUILD_DIR/$ELECTRON_PLATFORM
  PLATFORM_SCRIPT_DIR=$SCRIPT_DIR/$ELECTRON_PLATFORM
  platform_build_script=$PLATFORM_SCRIPT_DIR/build
  sudo rm -rf $PLATFORM_BUILD_DIR
  mkdir -p $PLATFORM_BUILD_DIR
  sudo rm -rf $CACHE_DIR/Gateblu-$ELECTRON_PLATFORM

  echo "** Checking for ElectronApp [$ELECTRON_PLATFORM]..."

  OUTPUT_ELECTRON_NAME=gateblu-v$ELECTRON_VERSION-$ELECTRON_PLATFORM
  ELECTRON_PLATFORM_ZIP=$OUTPUT_ELECTRON_NAME.zip
  if [ ! -f $ELECTRON_PLATFORM_ZIP ]; then
    echo "** Downloading ElectronApp ($ELECTRON_PLATFORM_ZIP) [$ELECTRON_PLATFORM]..."
    curl -LsO https://s3-us-west-2.amazonaws.com/gateblu/electron-binaries/$ELECTRON_PLATFORM_ZIP
    if [ $! ]; then
      exit 1
    fi
  fi

  echo "** Unzipping ElectronApp ($ELECTRON_PLATFORM_ZIP)[$ELECTRON_PLATFORM]..."
  mkdir -p $CACHE_DIR/$OUTPUT_ELECTRON_NAME
  unzip -qo $CACHE_DIR/electron/$ELECTRON_PLATFORM_ZIP -d $CACHE_DIR/$OUTPUT_ELECTRON_NAME

  echo "** Moving contents of ElectronApp [$ELECTRON_PLATFORM]..."
  cd $CACHE_DIR
  mkdir -p $PLATFORM_BUILD_DIR
  mv $OUTPUT_ELECTRON_NAME/* ../$ELECTRON_PLATFORM

  cd $PLATFORM_BUILD_DIR

  if [ ! -f $platform_build_script ]; then
    echo "** Could not find $platform_build_script"
    exit 1
  fi

  export ELECTRON_PLATFORM SCRIPT_DIR PLATFORM_BUILD_DIR ASSETS_DIR KEY_PASSWORD BUILD_DIR APP_DIR PLATFORM_SCRIPT_DIR APP_ARCHIVE

  echo "** Running platform script [$ELECTRON_PLATFORM]..."
  $platform_build_script

  if [ $! ]; then
    echo "** $platform_build_script Failed!"
    exit 1
  fi
done

cd $START_DIR
